spring:
  rabbitmq:
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        consumer:
          destination: consumer
          content-type: application/json
server:
  port: 0
